-- MySQL Script generated by MySQL Workbench
-- Sun Apr 15 01:10:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TARS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TARS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TARS` DEFAULT CHARACTER SET utf8 ;
USE `TARS` ;

-- -----------------------------------------------------
-- Table `TARS`.`Traffic Police`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TARS`.`Traffic Police` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(10) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Postcode` VARCHAR(5) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TARS`.`Police Officer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TARS`.`Police Officer` (
  `Badge_ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Rank` VARCHAR(45) NOT NULL,
  `Traffic Police_ID` INT NOT NULL,
  PRIMARY KEY (`Badge_ID`),
  INDEX `fk_Police Officer_Traffic Police1_idx` (`Traffic Police_ID` ASC),
  CONSTRAINT `fk_Police Officer_Traffic Police1`
    FOREIGN KEY (`Traffic Police_ID`)
    REFERENCES `TARS`.`Traffic Police` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TARS`.`ID_Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TARS`.`ID_Card` (
  `ID` INT NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Home Address` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(10) NOT NULL,
  `BirthDate` DATE NOT NULL,
  `SSN (Social Security Number [AMKA] )` INT NULL,
  `VATIN (Value Added Tax Identification Number [ΑΦΜ] )` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TARS`.`Car License`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TARS`.`Car License` (
  `LPN (License Plate Number)` INT NOT NULL,
  `VIN (Vehicle Identification Number)` INT NOT NULL,
  `Manufacturer` VARCHAR(45) NOT NULL,
  `Model` VARCHAR(45) NOT NULL,
  `Color` VARCHAR(45) NOT NULL,
  `cc (Cylinder Capacity)` VARCHAR(45) NOT NULL,
  `First Year of Circulation` YEAR NOT NULL,
  `Owner_ID_Card_ID` INT NOT NULL,
  PRIMARY KEY (`LPN (License Plate Number)`),
  INDEX `fk_Car License_ID_Card1_idx` (`Owner_ID_Card_ID` ASC),
  CONSTRAINT `fk_Car License_ID_Card1`
    FOREIGN KEY (`Owner_ID_Card_ID`)
    REFERENCES `TARS`.`ID_Card` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TARS`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TARS`.`Company` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(10) NOT NULL,
  `E - mail` VARCHAR(45) NOT NULL,
  `PCC (Parent Company Code) ID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Company_Company1_idx` (`PCC (Parent Company Code) ID` ASC),
  CONSTRAINT `fk_Company_Company1`
    FOREIGN KEY (`PCC (Parent Company Code) ID`)
    REFERENCES `TARS`.`Company` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TARS`.`Merchandise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TARS`.`Merchandise` (
  `TDN (Transport Document Number)` INT NOT NULL,
  `Type` VARCHAR(45) NULL,
  `Weight` FLOAT NULL,
  `Company_ID` INT NOT NULL,
  PRIMARY KEY (`TDN (Transport Document Number)`),
  INDEX `fk_Merchandise_Company1_idx` (`Company_ID` ASC),
  CONSTRAINT `fk_Merchandise_Company1`
    FOREIGN KEY (`Company_ID`)
    REFERENCES `TARS`.`Company` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TARS`.`Street Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TARS`.`Street Data` (
  `Street Code` INT NOT NULL,
  `Road Surface Type` VARCHAR(45) NOT NULL,
  `Road Surface State` VARCHAR(45) NOT NULL,
  `Speed Limit` INT NOT NULL,
  PRIMARY KEY (`Street Code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TARS`.`Traffic Police Accident Report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TARS`.`Traffic Police Accident Report` (
  `RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )` INT NOT NULL,
  `Report Date` DATE NOT NULL,
  `Revision Date` DATE NOT NULL,
  `Description` TEXT NOT NULL,
  `Latitude` FLOAT NOT NULL,
  `Longitude` FLOAT NOT NULL,
  `Draft_Police Officer_Badge_ID` INT NOT NULL,
  `Supervisor_Police Officer_Badge_ID1` INT NOT NULL,
  `Street Data_Street Code` INT NOT NULL,
  PRIMARY KEY (`RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )`),
  INDEX `fk_Accident Report_Police Officer1_idx` (`Draft_Police Officer_Badge_ID` ASC),
  INDEX `fk_Accident Report_Police Officer2_idx` (`Supervisor_Police Officer_Badge_ID1` ASC),
  INDEX `fk_Traffic Police Accident Report_Street Data1_idx` (`Street Data_Street Code` ASC),
  CONSTRAINT `fk_Accident Report_Police Officer1`
    FOREIGN KEY (`Draft_Police Officer_Badge_ID`)
    REFERENCES `TARS`.`Police Officer` (`Badge_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Accident Report_Police Officer2`
    FOREIGN KEY (`Supervisor_Police Officer_Badge_ID1`)
    REFERENCES `TARS`.`Police Officer` (`Badge_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Traffic Police Accident Report_Street Data1`
    FOREIGN KEY (`Street Data_Street Code`)
    REFERENCES `TARS`.`Street Data` (`Street Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TARS`.`Vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TARS`.`Vehicle` (
  `Serial Number` INT NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Estimated Speed` INT NOT NULL,
  `#Passengers` INT NOT NULL,
  `Insurance_Company_ID` INT NULL,
  `Merchandise_TDN (Transport Document Number)` INT NULL,
  `Car License_LPN (License Plate Number)` INT NULL,
  `Traffic Police Accident Report_RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )` INT NOT NULL,
  PRIMARY KEY (`Serial Number`, `Traffic Police Accident Report_RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )`),
  INDEX `fk_Vehicle_Car License1_idx` (`Car License_LPN (License Plate Number)` ASC),
  INDEX `fk_Vehicle_Company1_idx` (`Insurance_Company_ID` ASC),
  INDEX `fk_Vehicle_Merchandise1_idx` (`Merchandise_TDN (Transport Document Number)` ASC),
  INDEX `fk_Vehicle_Traffic Police Accident Report1_idx` (`Traffic Police Accident Report_RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )` ASC),
  CONSTRAINT `fk_Vehicle_Car License1`
    FOREIGN KEY (`Car License_LPN (License Plate Number)`)
    REFERENCES `TARS`.`Car License` (`LPN (License Plate Number)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehicle_Company1`
    FOREIGN KEY (`Insurance_Company_ID`)
    REFERENCES `TARS`.`Company` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehicle_Merchandise1`
    FOREIGN KEY (`Merchandise_TDN (Transport Document Number)`)
    REFERENCES `TARS`.`Merchandise` (`TDN (Transport Document Number)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehicle_Traffic Police Accident Report1`
    FOREIGN KEY (`Traffic Police Accident Report_RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )`)
    REFERENCES `TARS`.`Traffic Police Accident Report` (`RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TARS`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TARS`.`Person` (
  `ID` INT NOT NULL,
  `Property` VARCHAR(45) NULL,
  `Age` INT NULL,
  `ID_Card_ID` INT NULL,
  `Traffic Police Accident Report_RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )` INT NOT NULL,
  PRIMARY KEY (`ID`, `Traffic Police Accident Report_RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )`),
  INDEX `fk_Person_ID_Card1_idx` (`ID_Card_ID` ASC),
  INDEX `fk_Person_Traffic Police Accident Report1_idx` (`Traffic Police Accident Report_RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )` ASC),
  CONSTRAINT `fk_Person_ID_Card1`
    FOREIGN KEY (`ID_Card_ID`)
    REFERENCES `TARS`.`ID_Card` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Person_Traffic Police Accident Report1`
    FOREIGN KEY (`Traffic Police Accident Report_RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )`)
    REFERENCES `TARS`.`Traffic Police Accident Report` (`RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TARS`.`Passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TARS`.`Passenger` (
  `Seat` INT NULL,
  `Safety Equipment` VARCHAR(45) NULL,
  `Person_ID` INT NOT NULL,
  `Person_Traffic Police Accident Report_RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )` INT NOT NULL,
  `Vehicle_Serial Number` INT NOT NULL,
  PRIMARY KEY (`Person_ID`, `Person_Traffic Police Accident Report_RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )`),
  INDEX `fk_Passenger_Person1_idx` (`Person_ID` ASC, `Person_Traffic Police Accident Report_RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )` ASC),
  INDEX `fk_Passenger_Vehicle1_idx` (`Vehicle_Serial Number` ASC),
  CONSTRAINT `fk_Passenger_Person1`
    FOREIGN KEY (`Person_ID` , `Person_Traffic Police Accident Report_RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )`)
    REFERENCES `TARS`.`Person` (`ID` , `Traffic Police Accident Report_RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Passenger_Vehicle1`
    FOREIGN KEY (`Vehicle_Serial Number`)
    REFERENCES `TARS`.`Vehicle` (`Serial Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '																																																							';


-- -----------------------------------------------------
-- Table `TARS`.`Hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TARS`.`Hospital` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TARS`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TARS`.`Doctor` (
  `ID` INT NOT NULL,
  `License Number` INT NOT NULL,
  `Specialisation` VARCHAR(45) NOT NULL,
  `Hospital_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Doctor_Hospital1_idx` (`Hospital_ID` ASC),
  CONSTRAINT `fk_Doctor_Hospital1`
    FOREIGN KEY (`Hospital_ID`)
    REFERENCES `TARS`.`Hospital` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TARS`.`MAC (Medical Activities Catalog)`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TARS`.`MAC (Medical Activities Catalog)` (
  `ID` INT NOT NULL,
  `Description` TEXT NOT NULL,
  `PartsApplied` VARCHAR(45) NOT NULL,
  `Hospital_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_MAC (Medical Activities Catalog)_Hospital1`
    FOREIGN KEY (`Hospital_ID`)
    REFERENCES `TARS`.`Hospital` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TARS`.`Hospital Admission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TARS`.`Hospital Admission` (
  `IPC (Import Protocol Code)` INT NOT NULL,
  `Day of Admission` DATE NOT NULL,
  `Released Date` DATE NULL,
  `Severity` VARCHAR(45) NULL,
  `Wound Description` TEXT NULL,
  `Person_ID` INT NOT NULL,
  `Person_Traffic Police Accident Report_RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )` INT NOT NULL,
  `Hospital_ID` INT NOT NULL,
  PRIMARY KEY (`IPC (Import Protocol Code)`, `Hospital_ID`),
  INDEX `fk_Hospital Admission_Person1_idx` (`Person_ID` ASC, `Person_Traffic Police Accident Report_RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )` ASC),
  INDEX `fk_Hospital Admission_Hospital1_idx` (`Hospital_ID` ASC),
  CONSTRAINT `fk_Hospital Admission_Person1`
    FOREIGN KEY (`Person_ID` , `Person_Traffic Police Accident Report_RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )`)
    REFERENCES `TARS`.`Person` (`ID` , `Traffic Police Accident Report_RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hospital Admission_Hospital1`
    FOREIGN KEY (`Hospital_ID`)
    REFERENCES `TARS`.`Hospital` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TARS`.`Medication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TARS`.`Medication` (
  `Duration` TIME(10) NOT NULL,
  `Result` VARCHAR(45) NOT NULL,
  `MAC (Medical Activities Catalog)_ID` INT NOT NULL,
  PRIMARY KEY (`MAC (Medical Activities Catalog)_ID`),
  CONSTRAINT `fk_Medication_MAC (Medical Activities Catalog)1`
    FOREIGN KEY (`MAC (Medical Activities Catalog)_ID`)
    REFERENCES `TARS`.`MAC (Medical Activities Catalog)` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TARS`.`Driving License`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TARS`.`Driving License` (
  `DLN (Driving License Number)` INT NOT NULL,
  `Nationality` VARCHAR(45) NOT NULL,
  `DLC (Driving License Category)` VARCHAR(45) NOT NULL,
  `Date of Issue` DATE NOT NULL,
  `ID_Card_ID` INT NOT NULL,
  PRIMARY KEY (`DLN (Driving License Number)`),
  INDEX `fk_Driving License_ID_Card1_idx` (`ID_Card_ID` ASC),
  CONSTRAINT `fk_Driving License_ID_Card1`
    FOREIGN KEY (`ID_Card_ID`)
    REFERENCES `TARS`.`ID_Card` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TARS`.`Alcohol-Level Test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TARS`.`Alcohol-Level Test` (
  `Type` INT NOT NULL,
  `Time` TIME NOT NULL,
  `Result` TINYINT NOT NULL,
  PRIMARY KEY (`Type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TARS`.`Driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TARS`.`Driver` (
  `HCOC (Highway Code Offense Code)` INT NOT NULL,
  `Driving License_DLN (Driving License Number)` INT NULL,
  `Alcohol-Level Test_Type` INT NOT NULL,
  `Passenger_Person_ID` INT NOT NULL,
  `Passenger_Person_Traffic Police Accident Report_RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )` INT NOT NULL,
  INDEX `fk_Driver_Alcohol-Level Test1_idx` (`Alcohol-Level Test_Type` ASC),
  PRIMARY KEY (`Passenger_Person_ID`, `Passenger_Person_Traffic Police Accident Report_RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )`),
  CONSTRAINT `fk_Driver_Driving License`
    FOREIGN KEY (`Driving License_DLN (Driving License Number)`)
    REFERENCES `TARS`.`Driving License` (`DLN (Driving License Number)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Driver_Alcohol-Level Test1`
    FOREIGN KEY (`Alcohol-Level Test_Type`)
    REFERENCES `TARS`.`Alcohol-Level Test` (`Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Driver_Passenger1`
    FOREIGN KEY (`Passenger_Person_ID` , `Passenger_Person_Traffic Police Accident Report_RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )`)
    REFERENCES `TARS`.`Passenger` (`Person_ID` , `Person_Traffic Police Accident Report_RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TARS`.`Dangerous Merchandise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TARS`.`Dangerous Merchandise` (
  `Code` INT NULL,
  `Hazardousness Degree` INT NULL,
  `Merchandise_TDN (Transport Document Number)` INT NOT NULL,
  PRIMARY KEY (`Merchandise_TDN (Transport Document Number)`),
  CONSTRAINT `fk_Dangerous Merchandise_Merchandise1`
    FOREIGN KEY (`Merchandise_TDN (Transport Document Number)`)
    REFERENCES `TARS`.`Merchandise` (`TDN (Transport Document Number)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TARS`.`Insurance Accident Report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TARS`.`Insurance Accident Report` (
  `Report Date` DATE NOT NULL,
  `Estimated Damage` VARCHAR(45) NOT NULL,
  `Estimated Compensation` VARCHAR(45) NOT NULL,
  `Traffic Police Accident Report_RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )` INT NOT NULL,
  `Company_ID` INT NOT NULL,
  `Car License_LPN (License Plate Number)` INT NULL,
  INDEX `fk_Insurance Accident Report_Car License1_idx` (`Car License_LPN (License Plate Number)` ASC),
  PRIMARY KEY (`Traffic Police Accident Report_RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )`),
  INDEX `fk_Insurance Accident Report_Traffic Police Accident Report_idx` (`Traffic Police Accident Report_RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )` ASC),
  CONSTRAINT `fk_Insurance Accident Report_Company1`
    FOREIGN KEY (`Company_ID`)
    REFERENCES `TARS`.`Company` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Insurance Accident Report_Car License1`
    FOREIGN KEY (`Car License_LPN (License Plate Number)`)
    REFERENCES `TARS`.`Car License` (`LPN (License Plate Number)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Insurance Accident Report_Traffic Police Accident Report1`
    FOREIGN KEY (`Traffic Police Accident Report_RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )`)
    REFERENCES `TARS`.`Traffic Police Accident Report` (`RTAR_ID (Road Traffic Accident Report [ΔΟΤΑ] )`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TARS`.`Hospital Admission_has_Medication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TARS`.`Hospital Admission_has_Medication` (
  `Hospital Admission_IPC (Import Protocol Code)` INT NOT NULL,
  `Medication_MAC (Medical Activities Catalog)_ID` INT NOT NULL,
  PRIMARY KEY (`Hospital Admission_IPC (Import Protocol Code)`, `Medication_MAC (Medical Activities Catalog)_ID`),
  INDEX `fk_Hospital Admission_has_Medication_Medication1_idx` (`Medication_MAC (Medical Activities Catalog)_ID` ASC),
  INDEX `fk_Hospital Admission_has_Medication_Hospital Admission1_idx` (`Hospital Admission_IPC (Import Protocol Code)` ASC),
  CONSTRAINT `fk_Hospital Admission_has_Medication_Hospital Admission1`
    FOREIGN KEY (`Hospital Admission_IPC (Import Protocol Code)`)
    REFERENCES `TARS`.`Hospital Admission` (`IPC (Import Protocol Code)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hospital Admission_has_Medication_Medication1`
    FOREIGN KEY (`Medication_MAC (Medical Activities Catalog)_ID`)
    REFERENCES `TARS`.`Medication` (`MAC (Medical Activities Catalog)_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TARS`.`Medication_has_Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TARS`.`Medication_has_Doctor` (
  `Medication_MAC (Medical Activities Catalog)_ID` INT NOT NULL,
  `Doctor_ID` INT NOT NULL,
  PRIMARY KEY (`Medication_MAC (Medical Activities Catalog)_ID`, `Doctor_ID`),
  INDEX `fk_Medication_has_Doctor_Doctor1_idx` (`Doctor_ID` ASC),
  INDEX `fk_Medication_has_Doctor_Medication1_idx` (`Medication_MAC (Medical Activities Catalog)_ID` ASC),
  CONSTRAINT `fk_Medication_has_Doctor_Medication1`
    FOREIGN KEY (`Medication_MAC (Medical Activities Catalog)_ID`)
    REFERENCES `TARS`.`Medication` (`MAC (Medical Activities Catalog)_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medication_has_Doctor_Doctor1`
    FOREIGN KEY (`Doctor_ID`)
    REFERENCES `TARS`.`Doctor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
